# Generated by Django 4.2.21 on 2025-05-30 00:59

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description_rendered',
            field=markdownfield.models.RenderedMarkdownField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=markdownfield.models.MarkdownField(blank=True, null=True, rendered_field='description_rendered', verbose_name='Описание'),
        ),
    ]
